name: core
channels:
  - krande/label/dev
  - krande
  - conda-forge
dependencies:
  - numpy
  - h5py
  - ifcopenshell
  - pythonocc-core
  - python-gmsh
  - pyquaternion
  - trimesh
  - send2trash
  - meshio
  - pytexit
  - plotly
  - python-kaleido
  - calculix