name: core
channels:
  - conda-forge
  - krande
dependencies:
  - numpy
  - h5py
  - ifcopenshell
  - pythonocc-core
  - python-gmsh
  - pyquaternion
  - trimesh
  - occt >=7.7.2
  - send2trash
  - meshio
  - pytexit
  - plotly
  - python-kaleido
  - calculix